apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-demo.fullname" . }}
  labels:
    {{- include "app-demo.labels" . | nindent 4 }}
  namespace: argocd
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{.Values.service.nodePort}}
      protocol: TCP
      name: http
  selector:
    {{- include "app-demo.selectorLabels" . | nindent 4 }}
